[feat] emptyView 작성
boostcampwm2023/iOS07-traveline pull request #393
Opened 2024-01-12 11:48 UTC by otoolz

## 🌎 PR 요약
타임라인뷰에 타임라인이 비어있을 경우 emptyView를 보여줍니다.

🌱 작업한 브랜치
- feature/#384

## 📚 작업한 내용
타임라인뷰에 타임라인이 없을 경우, emptyView가 보여지도록 작업했습니다.

## 📍 참고 사항

- 타임라인셀의 영역에 엠티뷰의 레이아웃을 적용하고 싶었는데, 
컴포지셔널 레이아웃으로 된 콜렉션 뷰에서 각 영역의 위치를 얻기가 어려웠습니다.
그래서 현재는 콜렉션뷰의 백그라운드 뷰로 엠티뷰를 적용하고, 
엠티뷰에서는 기기마다 엠티뷰가 잘 보이도록 화면에 비례해서 바텀앵커를 조정하도록하였습니다.
(다른 기기에서도 확인하고 싶었는데, 시뮬에서는 이런 에러가 나서 확인은 못했습니다.)

![Screenshot 2024-01-12 at 7 55 11 PM](https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/09454635-72e1-46e0-97fa-1c78a40524dd)

- 현재 엠티뷰 처리를 cardlist가 비어있으면 띄워주도록 하고 있습니다. 그래서 타임라인 뷰로 넘어가면 타임라인이 작성된 뷰도 로딩이 끝날 때까지 엠티뷰가 떠있는 소소한 문제가 있습니다..

- 위에 두 참고사항 말고도 좋은 의견 주시면 감사하겠읍니다..

## 📸 스크린샷

https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/9e520975-9c58-4178-a89b-40ff83fe0e3d

## 관련 이슈
- Resolved: #384

2024-01-13 06:46 UTC, 0inn requested changes
넘 귀엽네요, , 🙃 collectionView 백그라운드로 둔 거 좋은 것 같습니다 !
- 검색 엠티뷰 추가랑
- 초기값 빼고 해당 엠티뷰 업데이트 방식
으로 변경하면 될 것 같아요 :)

2024-01-13 06:46 UTC, 0inn commented on iOS/traveline/Sources/DesignSystem/View/TLEmptyView.swift
> +class TLEmptyView: UIView {
p2; 검색 결과 EmptyView도 같이 만들어야 할 것 같아요 :)
여기 TLEmptyView에서 enum으로 분기해주면 좋을 것 같네요 ~

2024-01-13 06:46 UTC, 0inn commented on iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
> +                owner.timelineCollectionView.backgroundView?.isHidden = !cardlist.isEmpty
p1; 로딩중에는 로딩 프로그레스 바가, 서버 호출 후에 해당 엠티뷰가 뜨는 게 좋을 것 같아요 !
로딩은 1차 릴리즈 후에 가져가는 걸로 정했으니 .dropFirst() 메서드 추가해서 초기값인 경우 빼고 해당 엠티뷰 업데이트하도록 로직 변경하면 일단은 해결가능할 것 같습니다 ㅎㅎ

2024-01-13 08:03 UTC, kth1210 approved these changes
고생하셨습니다 기웅님!!
마찬가지로 위에 영인님 말씀주신 부분만 처리해주시면 좋을 것 같습니다!

저는 어프롭 해둘게용 ㅎ

2024-01-13 08:03 UTC, kth1210 commented on iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
>      }
잘 해결해주셨군요?? 👍👍

2024-01-15 15:40 UTC, otoolz commented on iOS/traveline/Sources/DesignSystem/View/TLEmptyView.swift
> +class TLEmptyView: UIView {
검색 결과, 타임라인 비었을 때 각각 화면입니당
<image src="https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/0dc53911-a08d-462a-a3bd-c112176d4bb6" width=200>

<image src="https://github.com/boostcampwm2023/iOS07-traveline/assets/91725382/d2b68d24-bc91-4d58-b388-48930362490a" width=200>

2024-01-15 15:56 UTC, otoolz commented on iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
> +                owner.timelineCollectionView.backgroundView?.isHidden = !cardlist.isEmpty
요게 약간 문제가 생겼습니다.. 
cardlist 초기 값이 []로 되어있어서 API 요청하고 받아왔을 때도 []면 state가 방출이 안되는 것 같습니다..
이것 때문인지는 확실히 모르겠는데 dropFirst()가 적용이 안되더라구요..

이 부분은 좀더 생각해보고 진행하도록 하겠습니다.

2024-01-15 16:03 UTC, kth1210 commented on iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
> +                owner.timelineCollectionView.backgroundView?.isHidden = !cardlist.isEmpty
아마 여기에서 `removeDuplicates()`를 걸어둬서 그렇지 않을까 싶습니당

간단하게는 timelineCardList가 Empty 일때를 처리해주는 바인딩을 하나 더 만들어도 괜찮지 않을까요..?

~~~swift
viewModel.state
        .map(\.timelineCardList)
        .dropFirst()
        .map({ $0.isEmpty })
        .withUnretained(self)
        .sink { owner, isEmpty in
            owner.timelineCollectionView.backgroundView?.isHidden = isEmpty
        }
        .store(in: &cancellables)
~~~

마크다운으로 쓴거라 문법이 정확하지 않을순 있으나 이런 느낌으로,,,,
바인딩 추가하지 않고 처리가 간단하게 가능하다면 그 방향이 더 좋은 것 같긴 합니다 ㅎ

2024-01-15 16:42 UTC, otoolz commented on iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
> +                owner.timelineCollectionView.backgroundView?.isHidden = !cardlist.isEmpty
오 ㅋㅋㅋ 안주무시고 계셨군요 ! 👍👍 바로 해보고 오겠읍니다 !

2024-01-15 17:39 UTC, otoolz commented on iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
> +                owner.timelineCollectionView.backgroundView?.isHidden = !cardlist.isEmpty
dropFirst()로 적용이 잘 안되더라구요 😂
타임라인 엠티뷰랑 검색 결과 엠티뷰에 각각 바인딩을 하나 더 만들어서 구현해줬습니다. 
태현님 감사해요!

2024-01-16 02:50 UTC, kth1210 commented on iOS/traveline/Sources/Feature/TimelineFeature/TimelineScene/VC/TimelineVC.swift
> +                owner.timelineCollectionView.backgroundView?.isHidden = !cardlist.isEmpty
앗 ㅋㅋㅋㅋㅋ 그렇군요! 늦은 시간까지 고생하셨습니다 기웅님 👍

2024-01-16 08:34 UTC, 0inn approved these changes
오 , , 잘 해결해주셨군요 ! 감사합니다 :)

2024-01-16 14:46 UTC, merged